### ISSUE TITLE
DAO: buscar

### ISSUE THREAD

**Issue by kenernot** [kenernot/ProjetoSorveteria#5]
@PedroEnju , verifique os métodos de buscar de todas as classes DAO, pois:

>             if (rs.first()) {
>                 while (rs.next()) {
>                 ....
>                 }
>             }

está fazendo com que ele pule o primeiro registro, sugiro um **do while**.

**Comment by barbosaadriano** [comment]
O Pedro já corrigiu e eu fiz o merge para ele!
