### ISSUE TITLE
Erro ao clicar no botão sair da tela de login

### ISSUE THREAD

**Issue by barbosaadriano** [kenernot/ProjetoSorveteria#6]
https://github.com/kenernot/ProjetoSorveteria/blob/f99d52a8e0d8dbb91bd32f405a51b6a3c874ec3f/FONTES/src/javafx/mvc/Main.java#L64

Se Clicar no botão sair na tela de login está explodindo o erro abaixo, por causa da linha acima!

![image](https://user-images.githubusercontent.com/15268237/57258996-7aa8bd80-7034-11e9-9017-61b5e95e2de8.png)

**Comment by kenernot** [comment]
#9

**Comment by barbosaadriano** [comment]
Resolvido e meged
