### ISSUE TITLE
Não está funcionando, ou será minha máquina?

### ISSUE THREAD

**Issue by barbosaadriano** [kenernot/ProjetoSorveteria#7]
Não obtive exito no login, "nem com reza de muié véia".
![image](https://user-images.githubusercontent.com/15268237/57259596-6796ed00-7036-11e9-95ed-ab1db5b662c7.png)

**Comment by kenernot** [comment]
É necessário comentar a seguinte linha no UsuarioDao (e também a linha que fecha a condição) para conseguir testar.
>             if (rs.first()) {

**Comment by barbosaadriano** [comment]
O Pedro já corrigiu o problema!
